---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/portfolio
  label: Portfolio
  create: none
  match: "*"
- type: directory
  path: content/blog
  label: Post
  create: documents
  match: "*"
  templates:
  - post
- type: directory
  path: content/anotresujet
  label: A notre sujet
  create: none
  match: "*"
- type: directory
  path: donnees
  label: Donn√©es
  create: documents
  match: "*"
  new_doc_ext: yml
- type: directory
  path: content/contacts
  label: Contacts
  create: none
  match: "*"
- type: document
  path: config.toml
  label: Configuration
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.80.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.80.0
